services:

  meteorologia_pipeline:
    build: .
    container_name: meteorologia_pipeline
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - TZ=America/Bogota
    command: sh -c "python -m src.extract && python -m src.transform && python -m src.load"

  airflow:
    image: apache/airflow:2.10.4
    container_name: airflow
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./config:/opt/airflow/config
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - PYTHONPATH=/opt/airflow
    command: standalone